services:
  hono-app:
    build: .
    container_name: firebase-fcm-api
    ports:
      - "92:3000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: mysql://amiminn:amiminn@mariadb_container:3306/fcm_api
    command: >
      sh -c "bun install && bun run prisma migrate deploy && bun run dev"

networks:
  default:
    name: amiminn_network
    external: true
