CREATE TABLE IF NOT EXISTS "Device" (
  "id" TEXT PRIMARY KEY,
  "deviceKey" TEXT NOT NULL UNIQUE,
  "token" TEXT NOT NULL UNIQUE,
  "topic" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "Device_deviceKey_key"
ON "Device" ("deviceKey");

CREATE UNIQUE INDEX IF NOT EXISTS "Device_token_key"
ON "Device" ("token");
